# Generated by Django 3.1.1 on 2020-09-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administratorx'), ('Maintainer', 'Maintainerx')], default='Maintainer', max_length=50),
        ),
    ]
