# Generated by Django 3.1.1 on 2020-09-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200921_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='screen_size',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Desktop', 'Desktop')], max_length=200),
        ),
    ]
