# Generated by Django 3.1.1 on 2020-09-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200919_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='is_admin',
        ),
    ]
