# Generated by Django 3.1.1 on 2020-09-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200921_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='photo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
