# Generated by Django 3.1.1 on 2020-09-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200923_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
